### PR TITLE
Updated Guzzle dependency to 6.x version

### PR DESCRIPTION
**Pull request by akalongman**
This is a backward incompatible 2.x version of current library.

Features:

- Reformatted code to PSR-2 coding standard
- Updated Guzzle to 6.x version
- Increased minimum php requirement to 5.5

### CODE REVIEW

**Comment by e1himself** [comment]
Might be worth merging it to `2.x` branch or something

**Comment by e1himself** [comment]
ping @mkdynamic

**Comment by mkdynamic** [comment]
Thanks so much @akalongman, this looks great -- we're taking a look!

Will likely just merge into master @e1himself since that is the edge branch.

Do you happen to know what the adoption is for 5.5+? Will investigate but if you have any sense would be super helpful.

**Comment by e1himself** [comment]
@mkdynamic 

Regarding PHP 5.5. I think it shouldn't be about adoption. 
5.5 is on end-of-life now since mid 2016. No security patches, no updates.
So users *should* upgrade (http://php.net/supported-versions.php).

For those who can't upgrade and is still using 5.3 ... 5.5 there's a 1.x version of *delighted-php*.

**Comment by akalongman** [comment]
@mkdynamic
> Do you happen to know what the adoption is for 5.5

Its minimum version supported by Guzzle 6, this is main reason why I increased minimum version for current library too. Also @e1himself is right, 5.5 is not supported anymore and highly recommended upgrade to >=7.0

**Comment by salbertson** [comment]
@akalongman would you mind taking a look at the conflicts now that https://github.com/delighted/delighted-php/pull/9 has been merged?

**Comment by akalongman** [comment]
@salbertson conflicts resolved

**Comment by mkdynamic** [comment]
Thanks @akalongman. Preparing `2.0.0-beta` release.

**Comment by mkdynamic** [comment]
Beta release up, please check it out and let us know how it goes:
https://packagist.org/packages/delighted/delighted#v2.0.0-beta

**Pull request merged**
