### PR TITLE
Update guzzle auth when calling setApiKey

### LINKED ISSUE #8: `Client::setApiKey` doesn't change guzzle auth
Calling `Client::setApiKey` only changes the static property, it doesn't update the underlying guzzle client's auth options. So it's effectively useless if you have multiple API keys and switch between them.

### PR DESCRIPTION
**Pull request by rnewton**
This fixes https://github.com/delighted/delighted-php/issues/8

The problem is that we are running a background job that processes our survey subscriptions. Customers are created in delighted using the API key corresponding to their company. Unfortunately since the delighted client is static, only the first instance gets the API key. Changing the API key doesn't change the HTTP adapter's key and so the request doesn't end up in the right spot.

### CODE REVIEW

**Comment by mkdynamic** [comment]
Thanks @rnewton. I think this potentially touches upon another issue, since the arguments to `Client.getInstance` are only used once -- that is possibly confusing also.

Perhaps an even better way would be to instantiate a client manually, and inject the API key, like `$client = new Client(array('apiKey' => 'xyzzy'))` -- basically avoid using a shared instance when you are going to be using multiple API keys. Would that approach work for your scenario?

This pattern follows our other libraries more closely:

- https://github.com/delighted/delighted-ruby#-advanced-configuration--testing
- https://github.com/delighted/delighted-node#-advanced-configuration--testing
- https://github.com/delighted/delighted-python#-advanced-configuration--testing

**Comment by rnewton** [comment]
If we can get rid of the static/singleton pattern the problem goes away entirely. I wasn't sure if there was some other scenario that the singleton was necessary for, however.

**Comment by rnewton** [comment]
This is a much larger change and actually changes the interface slightly (`get`, `post`, `put` and `delete` are no longer static).

**Comment by mkdynamic** [comment]
Thanks @rnewton, this looks really great. Much more flexible and consistent with the other libraries. Should merge soon.

**Comment by rnewton** [comment]
Great! Do you have an idea on when this can be merged? Also, can this be tagged so that composer/packagist picks it up?

**Comment by mkdynamic** [comment]
@rnewton We're looking at this now, should have a pre release up this week.

If we also merged https://github.com/delighted/delighted-php/pull/10, would that work for your case -- for the version of PHP and related dependencies you're using? If not, no problem, we could release this as a 1.x release in addition to that 2.x release.

**Comment by rnewton** [comment]
I like the changes in #10 but I would be surprised if this one merged cleanly with that one. I'm happy to help anyway I can though

**Comment by salbertson** [comment]
Thanks again @rnewton! This looks good to me. 👍

**Comment by e1himself** [comment]
> 1.x release

I think these changes shouldn't make it into 1.x release at it's breaking BC as @rnewton mentioned:

> This is a much larger change and actually changes the interface slightly (get, post, put and delete are no longer static).

So it might be worth to roll it out along with Guzzle 6 branch as 2.0

**Comment by mkdynamic** [comment]
Yea, scratch what I said about the possibility of including this into 1.x release. It is potentially breaking and so we should bump the major version. @salbertson Can you prep a 2.0.0-beta instead? :)

**Comment by mkdynamic** [comment]
Beta release up, please check it out and let us know how it goes:
https://packagist.org/packages/delighted/delighted#v2.0.0-beta

**Comment by rnewton** [comment]
@mkdynamic : one problem with the new beta vs this PR. `Client::__construct` is protected again. It needs to be public in order to chose to use a shared client or new client per request.

**Comment by mkdynamic** [comment]
Ah yea, sorry @rnewton. Pushed a fix in https://github.com/delighted/delighted-php/commit/1d99eed325e39c8203dab345e1047ee393717205 -- look good? Just pushed a `2.0.0-beta.1` release with that update included.

**Comment by rnewton** [comment]
Perfect. Thanks!

**Pull request merged**
