### PR TITLE
Booleans are serialized to 0/1 by http_build_query

### PR DESCRIPTION
**Pull request by mkdynamic**
HTTP API expects them as true/false strings, when body is form encoded.

Attached failing test case:

```
1) PeopleTest::testCreatingOrUpdatingAPersonWithoutSending
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'email=foo%40bar.com&send=false'
+'email=foo%40bar.com&send=0'
```

### CODE REVIEW

**Comment by geoff-parsons** [comment]
@mkdynamic Doesn't appear to be a setting in Guzzle to do this for us so just a quick little hack to adjust any bools to `'true'` | `'false'`.

**Review by mkdynamic — COMMENTED** [review]
Looks good @skhisma -- once merged can you update the `CHANGELOG` and prep a 2.0.1 prerelease?

**Review by mkdynamic — COMMENTED** [review]
Not sure if the CI failures are branch specific or same on master, but plz double check those also. @skhisma

**Comment by geoff-parsons** [comment]
Looks like an issue with Composer on HHVM, I'll take a look.

**Pull request merged**
