### PR TITLE
Restricted Guzzle version to 3.8.*

### PR DESCRIPTION
**Pull request by e1himself**
At least test suite is incompatible with 3.9.*

### CODE REVIEW

**Comment by mkdynamic** [comment]
@e1himself Thanks for this. I think we'll need to fix the test suite, or find some other solution because while this fixes the issue, it also will break https://github.com/delighted/delighted-php/issues/1#issuecomment-97471028.

**Comment by e1himself** [comment]
Hm. You're right!

So fixing the tests seems the best approach for me. I think I've fixed it
previously by moving initialization code from constructor to setUp() method
on MetricsTest class.

Sorry, I won't have time to fix it myself until October. Vacation :)
16 вер. 2015 23:29 "Mark Dodwell" notifications@github.com пише:

**Comment by mkdynamic** [comment]
@kindjar Is this related to https://github.com/delighted/delighted-php/commit/0db3581cc8488ff33f912b50dc4b57a003e42c18?

**Comment by kindjar** [comment]
Yes, https://github.com/delighted/delighted-php/commit/0db3581cc8488ff33f912b50dc4b57a003e42c18 fixes the issue with Guzzle 3.9, so this issue can be closed. Thanks for the reminder.

**Pull request closed without merging**
